// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDWfxpMDbrz3poshF-vgNc2TBW3IyqStU',
    appId: '1:453751060369:web:9015118dff91d03e1b4c30',
    messagingSenderId: '453751060369',
    projectId: 'nunut-da274',
    authDomain: 'nunut-da274.firebaseapp.com',
    storageBucket: 'nunut-da274.appspot.com',
    measurementId: 'G-KWEFP8VFD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALkckblym7uE-p-nn61GhzJ8R9w_6YGOU',
    appId: '1:453751060369:android:ac42caa294ea67861b4c30',
    messagingSenderId: '453751060369',
    projectId: 'nunut-da274',
    storageBucket: 'nunut-da274.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJpNoA-fdGF0pPwC6mLJYvkgbjgWLf_WU',
    appId: '1:453751060369:ios:54cd2d49ccf55d411b4c30',
    messagingSenderId: '453751060369',
    projectId: 'nunut-da274',
    storageBucket: 'nunut-da274.appspot.com',
    iosClientId: '453751060369-r5uor4jskn7mtpf485kdv1qli425r4bo.apps.googleusercontent.com',
    iosBundleId: 'com.example.nunutApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJpNoA-fdGF0pPwC6mLJYvkgbjgWLf_WU',
    appId: '1:453751060369:ios:54cd2d49ccf55d411b4c30',
    messagingSenderId: '453751060369',
    projectId: 'nunut-da274',
    storageBucket: 'nunut-da274.appspot.com',
    iosClientId: '453751060369-r5uor4jskn7mtpf485kdv1qli425r4bo.apps.googleusercontent.com',
    iosBundleId: 'com.example.nunutApplication',
  );
}
